language: python

python:
  - "2.7"

install:
  - pip install -r requirements.txt

before_script:
  - cp example_config .coffeerc

script:
  - flake8
  - PYTHONPATH=$PWD python coffee/tests.py 

services:
  - redis-server
